//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDuckService")]
    public interface IDuckService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuckService/GetDuck", ReplyAction="http://tempuri.org/IDuckService/GetDuckResponse")]
        WcfServiceLibrary.Duck GetDuck(WcfServiceLibrary.Duck composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuckService/GetDuck", ReplyAction="http://tempuri.org/IDuckService/GetDuckResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary.Duck> GetDuckAsync(WcfServiceLibrary.Duck composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuckServiceChannel : WcfClient.ServiceReference1.IDuckService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuckServiceClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IDuckService>, WcfClient.ServiceReference1.IDuckService {
        
        public DuckServiceClient() {
        }
        
        public DuckServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DuckServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuckServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary.Duck GetDuck(WcfServiceLibrary.Duck composite) {
            return base.Channel.GetDuck(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary.Duck> GetDuckAsync(WcfServiceLibrary.Duck composite) {
            return base.Channel.GetDuckAsync(composite);
        }
    }
}
